[package]
name = "mania-acc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"

[target.'cfg(unix)'.dependencies]
termios = "0.3.3"
